import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NotFound from "@/components/not-found";
import { GlobalProvider } from "@/app/GlobalProvider";
import { getServerSession } from "next-auth";
import Link from 'next/link';
import Logout from './logout';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className="w-full h-full">
        <GlobalProvider>
        <nav>
          {!!session && 
            <Logout />
          }
          {!session && 
          <Link href="/login">Login</Link>}
        </nav>
          {children}
        </GlobalProvider>
      </body>
    </html>
  );

  //<Navbar />
}
